name: test-workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install node js 
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: checkout 
        uses: actions/checkout@v4.1.6
      - name: cache
        uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      - name: install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: lint files
        run: npm run lint