name: test-github-action
on:
  push:
    branches:
      - main
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    name: My first jobs
  my_second_job:
    runs-on: ubuntu-latest
    name: My second job
    steps:
      - name: test
        run: echo "Helloworld !!"
