name: test-workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - uses: actions/checkout@v4.1.6
      - uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm install
      - run: npm run lint