name: deploy-to-github-pages
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node js
        uses: actions/setup-node@v5
        with:
          node-version: '22.13.0'
      - name: print Node version
        run: node -v
      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Run test
        run: npm run lint
      - name: Completed job
        run: echo "Completed jobs"
  build:
    needs: 
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node js
        uses: actions/setup-node@v5
        with:
          node-version: '22.13.0'
      - name: print Node version
        run: node -v
      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: build app
        run: npm run build
  deploy:
    needs: 
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "Deployment completed"
    