name: deploy-to-github-pages
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node js
        uses: actions/setup-node@v5
        with:
          node-version: '22.13.0'
      - name: print Node version
        run: node -v
      - name: install deps
        run: npm install
      - name: Run test
        run: npm run test
      - name: Completed job
        run: echo "Completed jobs"